[config]
    [config.input]
        url = "http://127.0.0.1:9200"
        username = ""
        password = ""

    [config.output]
        url = "http://127.0.0.1:9200"
        username = ""
        password = ""

    [config.indices]
        indices-no-timestamp = ["transactions"]
        indices-name-on-dest = ["something"]
        [config.indices.with-timestamp]
            enabled = false
            num-parallel-writes = 20
            blockchain-start-time = 1596117600 # mainnet start time ( for testnet will be a different start time)
            end-time = 0 # 0 - current timestamp OR a provided end time for interval
            indices-with-timestamp = ["accountsesdt", "tokens", "blocks", "receipts", "transactions","miniblocks", "rounds",  "accountshistory", "scresults", "accountsesdthistory", "scdeploys", "logs", "operations"]
